# -*- coding: utf-8 -*-
"""Sales_Data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11pJoTwkbGiu1Th9vogpLwxuGJwbgeOmG
"""

import sqlite3

# Create database in current session
conn = sqlite3.connect("sales_data.db")
cursor = conn.cursor()

# Create table
cursor.execute("""
CREATE TABLE IF NOT EXISTS sales (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    product TEXT,
    quantity INTEGER,
    price REAL
)
""")

# Insert sample data
sample_data = [
    ("Laptop", 3, 800),
    ("Laptop", 2, 820),
    ("Phone", 5, 500),
    ("Phone", 4, 520),
    ("Headphones", 10, 50),
    ("Headphones", 7, 55),
    ("Monitor", 4, 200),
    ("Monitor", 3, 210)
]
cursor.executemany("INSERT INTO sales (product, quantity, price) VALUES (?, ?, ?)", sample_data)

# Commit & close
conn.commit()
conn.close()

print("Database created and sample data inserted!")

import pandas as pd
import matplotlib.pyplot as plt
import sqlite3

# Connect to DB
conn = sqlite3.connect("sales_data.db")

# Run SQL query
query = """
SELECT
    product,
    SUM(quantity) AS total_qty,
    SUM(quantity * price) AS revenue
FROM sales
GROUP BY product
"""
df = pd.read_sql_query(query, conn)
conn.close()

# Print results
print(df)

# Plot bar chart
plt.figure(figsize=(6, 4))
plt.bar(df['product'], df['revenue'], color='skyblue')
plt.xlabel("Product")
plt.ylabel("Revenue")
plt.title("Revenue by Product")
plt.tight_layout()
plt.show()

plt.savefig("sales_data_chart.png")